# Generated by Django 4.2.6 on 2023-10-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adi', models.CharField(max_length=50)),
                ('urun_aciklamasi', models.CharField(max_length=100)),
                ('urun_fotografi', models.CharField(max_length=500)),
            ],
        ),
    ]
