# Generated by Django 4.2.6 on 2023-10-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0002_kategori_urun_urun_kategorisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='urun_kategorisi',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
    ]
